package top.zydse.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import top.zydse.model.Collection;
import top.zydse.model.CollectionExample;

public interface CollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLECTION
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    long countByExample(CollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLECTION
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    int deleteByExample(CollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLECTION
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLECTION
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    int insert(Collection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLECTION
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    int insertSelective(Collection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLECTION
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    List<Collection> selectByExampleWithRowbounds(CollectionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLECTION
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    List<Collection> selectByExample(CollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLECTION
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    Collection selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLECTION
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") Collection record, @Param("example") CollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLECTION
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    int updateByExample(@Param("record") Collection record, @Param("example") CollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLECTION
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    int updateByPrimaryKeySelective(Collection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLECTION
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    int updateByPrimaryKey(Collection record);
}