package top.zydse.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import top.zydse.model.Role;
import top.zydse.model.RoleExample;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    long countByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    int deleteByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    List<Role> selectByExampleWithRowbounds(RoleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    List<Role> selectByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    int updateByExample(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    int updateByPrimaryKey(Role record);
}