package top.zydse.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import top.zydse.model.RolePermission;
import top.zydse.model.RolePermissionExample;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_PERMISSION
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    long countByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_PERMISSION
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    int deleteByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_PERMISSION
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_PERMISSION
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    int insert(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_PERMISSION
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    int insertSelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_PERMISSION
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    List<RolePermission> selectByExampleWithRowbounds(RolePermissionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_PERMISSION
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    List<RolePermission> selectByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_PERMISSION
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    RolePermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_PERMISSION
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    int updateByExampleSelective(@Param("record") RolePermission record, @Param("example") RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_PERMISSION
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    int updateByExample(@Param("record") RolePermission record, @Param("example") RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_PERMISSION
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    int updateByPrimaryKeySelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_PERMISSION
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    int updateByPrimaryKey(RolePermission record);
}