package top.zydse.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import top.zydse.model.ThumbHistory;
import top.zydse.model.ThumbHistoryExample;

public interface ThumbHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB_HISTORY
     *
     * @mbg.generated Wed Apr 01 15:39:55 CST 2020
     */
    long countByExample(ThumbHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB_HISTORY
     *
     * @mbg.generated Wed Apr 01 15:39:55 CST 2020
     */
    int deleteByExample(ThumbHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB_HISTORY
     *
     * @mbg.generated Wed Apr 01 15:39:55 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB_HISTORY
     *
     * @mbg.generated Wed Apr 01 15:39:55 CST 2020
     */
    int insert(ThumbHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB_HISTORY
     *
     * @mbg.generated Wed Apr 01 15:39:55 CST 2020
     */
    int insertSelective(ThumbHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB_HISTORY
     *
     * @mbg.generated Wed Apr 01 15:39:55 CST 2020
     */
    List<ThumbHistory> selectByExampleWithRowbounds(ThumbHistoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB_HISTORY
     *
     * @mbg.generated Wed Apr 01 15:39:55 CST 2020
     */
    List<ThumbHistory> selectByExample(ThumbHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB_HISTORY
     *
     * @mbg.generated Wed Apr 01 15:39:55 CST 2020
     */
    ThumbHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB_HISTORY
     *
     * @mbg.generated Wed Apr 01 15:39:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") ThumbHistory record, @Param("example") ThumbHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB_HISTORY
     *
     * @mbg.generated Wed Apr 01 15:39:55 CST 2020
     */
    int updateByExample(@Param("record") ThumbHistory record, @Param("example") ThumbHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB_HISTORY
     *
     * @mbg.generated Wed Apr 01 15:39:55 CST 2020
     */
    int updateByPrimaryKeySelective(ThumbHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB_HISTORY
     *
     * @mbg.generated Wed Apr 01 15:39:55 CST 2020
     */
    int updateByPrimaryKey(ThumbHistory record);
}