package top.zydse.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import top.zydse.model.Verification;
import top.zydse.model.VerificationExample;

public interface VerificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification
     *
     * @mbg.generated Fri Mar 27 23:39:21 CST 2020
     */
    long countByExample(VerificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification
     *
     * @mbg.generated Fri Mar 27 23:39:21 CST 2020
     */
    int deleteByExample(VerificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification
     *
     * @mbg.generated Fri Mar 27 23:39:21 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification
     *
     * @mbg.generated Fri Mar 27 23:39:21 CST 2020
     */
    int insert(Verification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification
     *
     * @mbg.generated Fri Mar 27 23:39:21 CST 2020
     */
    int insertSelective(Verification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification
     *
     * @mbg.generated Fri Mar 27 23:39:21 CST 2020
     */
    List<Verification> selectByExampleWithRowbounds(VerificationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification
     *
     * @mbg.generated Fri Mar 27 23:39:21 CST 2020
     */
    List<Verification> selectByExample(VerificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification
     *
     * @mbg.generated Fri Mar 27 23:39:21 CST 2020
     */
    Verification selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification
     *
     * @mbg.generated Fri Mar 27 23:39:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") Verification record, @Param("example") VerificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification
     *
     * @mbg.generated Fri Mar 27 23:39:21 CST 2020
     */
    int updateByExample(@Param("record") Verification record, @Param("example") VerificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification
     *
     * @mbg.generated Fri Mar 27 23:39:21 CST 2020
     */
    int updateByPrimaryKeySelective(Verification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification
     *
     * @mbg.generated Fri Mar 27 23:39:21 CST 2020
     */
    int updateByPrimaryKey(Verification record);
}