package top.zydse.model;

public class Collection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLLECTION.ID
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLLECTION.USER_ID
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLLECTION.QUESTION_ID
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    private Long questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COLLECTION.GMT_CREATE
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLLECTION.ID
     *
     * @return the value of COLLECTION.ID
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLLECTION.ID
     *
     * @param id the value for COLLECTION.ID
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLLECTION.USER_ID
     *
     * @return the value of COLLECTION.USER_ID
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLLECTION.USER_ID
     *
     * @param userId the value for COLLECTION.USER_ID
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLLECTION.QUESTION_ID
     *
     * @return the value of COLLECTION.QUESTION_ID
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLLECTION.QUESTION_ID
     *
     * @param questionId the value for COLLECTION.QUESTION_ID
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COLLECTION.GMT_CREATE
     *
     * @return the value of COLLECTION.GMT_CREATE
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COLLECTION.GMT_CREATE
     *
     * @param gmtCreate the value for COLLECTION.GMT_CREATE
     *
     * @mbg.generated Fri Apr 17 20:16:03 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}