package top.zydse.model;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.QUESTION_ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    private Long questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.REVIEWER
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    private Long reviewer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.CONTENT
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.GMT_CREATE
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.GMT_MODIFIED
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.THUMB_COUNT
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    private Integer thumbCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.SUB_COMMENT_COUNT
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    private Integer subCommentCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.ID
     *
     * @return the value of comment.ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.ID
     *
     * @param id the value for comment.ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.QUESTION_ID
     *
     * @return the value of comment.QUESTION_ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.QUESTION_ID
     *
     * @param questionId the value for comment.QUESTION_ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.REVIEWER
     *
     * @return the value of comment.REVIEWER
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public Long getReviewer() {
        return reviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.REVIEWER
     *
     * @param reviewer the value for comment.REVIEWER
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public void setReviewer(Long reviewer) {
        this.reviewer = reviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.CONTENT
     *
     * @return the value of comment.CONTENT
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.CONTENT
     *
     * @param content the value for comment.CONTENT
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.GMT_CREATE
     *
     * @return the value of comment.GMT_CREATE
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.GMT_CREATE
     *
     * @param gmtCreate the value for comment.GMT_CREATE
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.GMT_MODIFIED
     *
     * @return the value of comment.GMT_MODIFIED
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.GMT_MODIFIED
     *
     * @param gmtModified the value for comment.GMT_MODIFIED
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.THUMB_COUNT
     *
     * @return the value of comment.THUMB_COUNT
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public Integer getThumbCount() {
        return thumbCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.THUMB_COUNT
     *
     * @param thumbCount the value for comment.THUMB_COUNT
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public void setThumbCount(Integer thumbCount) {
        this.thumbCount = thumbCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.SUB_COMMENT_COUNT
     *
     * @return the value of comment.SUB_COMMENT_COUNT
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public Integer getSubCommentCount() {
        return subCommentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.SUB_COMMENT_COUNT
     *
     * @param subCommentCount the value for comment.SUB_COMMENT_COUNT
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public void setSubCommentCount(Integer subCommentCount) {
        this.subCommentCount = subCommentCount;
    }
}