package top.zydse.model;

public class QuestionTag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_tag.ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_tag.QUESTION_ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    private Long questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_tag.TAG_ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    private Integer tagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_tag.GMT_CREATE
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_tag.ID
     *
     * @return the value of question_tag.ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_tag.ID
     *
     * @param id the value for question_tag.ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_tag.QUESTION_ID
     *
     * @return the value of question_tag.QUESTION_ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_tag.QUESTION_ID
     *
     * @param questionId the value for question_tag.QUESTION_ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_tag.TAG_ID
     *
     * @return the value of question_tag.TAG_ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_tag.TAG_ID
     *
     * @param tagId the value for question_tag.TAG_ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_tag.GMT_CREATE
     *
     * @return the value of question_tag.GMT_CREATE
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_tag.GMT_CREATE
     *
     * @param gmtCreate the value for question_tag.GMT_CREATE
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}