package top.zydse.model;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.ID
     *
     * @mbg.generated Sat Mar 28 21:45:12 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.ROLE_TYPE
     *
     * @mbg.generated Sat Mar 28 21:45:12 CST 2020
     */
    private String roleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.ROLE_NAME
     *
     * @mbg.generated Sat Mar 28 21:45:12 CST 2020
     */
    private String roleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.ID
     *
     * @return the value of ROLE.ID
     *
     * @mbg.generated Sat Mar 28 21:45:12 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.ID
     *
     * @param id the value for ROLE.ID
     *
     * @mbg.generated Sat Mar 28 21:45:12 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.ROLE_TYPE
     *
     * @return the value of ROLE.ROLE_TYPE
     *
     * @mbg.generated Sat Mar 28 21:45:12 CST 2020
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.ROLE_TYPE
     *
     * @param roleType the value for ROLE.ROLE_TYPE
     *
     * @mbg.generated Sat Mar 28 21:45:12 CST 2020
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType == null ? null : roleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.ROLE_NAME
     *
     * @return the value of ROLE.ROLE_NAME
     *
     * @mbg.generated Sat Mar 28 21:45:12 CST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.ROLE_NAME
     *
     * @param roleName the value for ROLE.ROLE_NAME
     *
     * @mbg.generated Sat Mar 28 21:45:12 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }
}