package top.zydse.model;

public class SubComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_comment.ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_comment.QUESTION_ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    private Long questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_comment.COMMENT_ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    private Long commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_comment.REVIEWER
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    private Long reviewer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_comment.CONTENT
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_comment.GMT_CREATE
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_comment.GMT_MODIFIED
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_comment.ID
     *
     * @return the value of sub_comment.ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_comment.ID
     *
     * @param id the value for sub_comment.ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_comment.QUESTION_ID
     *
     * @return the value of sub_comment.QUESTION_ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_comment.QUESTION_ID
     *
     * @param questionId the value for sub_comment.QUESTION_ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_comment.COMMENT_ID
     *
     * @return the value of sub_comment.COMMENT_ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_comment.COMMENT_ID
     *
     * @param commentId the value for sub_comment.COMMENT_ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_comment.REVIEWER
     *
     * @return the value of sub_comment.REVIEWER
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public Long getReviewer() {
        return reviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_comment.REVIEWER
     *
     * @param reviewer the value for sub_comment.REVIEWER
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public void setReviewer(Long reviewer) {
        this.reviewer = reviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_comment.CONTENT
     *
     * @return the value of sub_comment.CONTENT
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_comment.CONTENT
     *
     * @param content the value for sub_comment.CONTENT
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_comment.GMT_CREATE
     *
     * @return the value of sub_comment.GMT_CREATE
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_comment.GMT_CREATE
     *
     * @param gmtCreate the value for sub_comment.GMT_CREATE
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_comment.GMT_MODIFIED
     *
     * @return the value of sub_comment.GMT_MODIFIED
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_comment.GMT_MODIFIED
     *
     * @param gmtModified the value for sub_comment.GMT_MODIFIED
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}