package top.zydse.model;

public class ThumbHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb_history.ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb_history.THUMB_USER
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    private Long thumbUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb_history.COMMENT_ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    private Long commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb_history.GMT_CREATE
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb_history.ID
     *
     * @return the value of thumb_history.ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb_history.ID
     *
     * @param id the value for thumb_history.ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb_history.THUMB_USER
     *
     * @return the value of thumb_history.THUMB_USER
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public Long getThumbUser() {
        return thumbUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb_history.THUMB_USER
     *
     * @param thumbUser the value for thumb_history.THUMB_USER
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public void setThumbUser(Long thumbUser) {
        this.thumbUser = thumbUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb_history.COMMENT_ID
     *
     * @return the value of thumb_history.COMMENT_ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb_history.COMMENT_ID
     *
     * @param commentId the value for thumb_history.COMMENT_ID
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb_history.GMT_CREATE
     *
     * @return the value of thumb_history.GMT_CREATE
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb_history.GMT_CREATE
     *
     * @param gmtCreate the value for thumb_history.GMT_CREATE
     *
     * @mbg.generated Sat Mar 28 19:17:04 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}