package top.zydse.model;

public class ViewHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEW_HISTORY.ID
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEW_HISTORY.VIEWER
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    private Long viewer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEW_HISTORY.QUESTION_ID
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    private Long questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEW_HISTORY.GMT_CREATE
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEW_HISTORY.GMT_MODIFIED
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEW_HISTORY.ID
     *
     * @return the value of VIEW_HISTORY.ID
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEW_HISTORY.ID
     *
     * @param id the value for VIEW_HISTORY.ID
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEW_HISTORY.VIEWER
     *
     * @return the value of VIEW_HISTORY.VIEWER
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    public Long getViewer() {
        return viewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEW_HISTORY.VIEWER
     *
     * @param viewer the value for VIEW_HISTORY.VIEWER
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    public void setViewer(Long viewer) {
        this.viewer = viewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEW_HISTORY.QUESTION_ID
     *
     * @return the value of VIEW_HISTORY.QUESTION_ID
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEW_HISTORY.QUESTION_ID
     *
     * @param questionId the value for VIEW_HISTORY.QUESTION_ID
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEW_HISTORY.GMT_CREATE
     *
     * @return the value of VIEW_HISTORY.GMT_CREATE
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEW_HISTORY.GMT_CREATE
     *
     * @param gmtCreate the value for VIEW_HISTORY.GMT_CREATE
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEW_HISTORY.GMT_MODIFIED
     *
     * @return the value of VIEW_HISTORY.GMT_MODIFIED
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEW_HISTORY.GMT_MODIFIED
     *
     * @param gmtModified the value for VIEW_HISTORY.GMT_MODIFIED
     *
     * @mbg.generated Tue Apr 14 20:29:00 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}