package top.zydse.dto;

public class VerificationDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verification.ID
     *
     * @mbg.generated Fri Mar 27 23:39:21 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verification.PHONE_NUMBER
     *
     * @mbg.generated Fri Mar 27 23:39:21 CST 2020
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verification.CODE
     *
     * @mbg.generated Fri Mar 27 23:39:21 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verification.GMT_CREATE
     *
     * @mbg.generated Fri Mar 27 23:39:21 CST 2020
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verification.ID
     *
     * @return the value of verification.ID
     *
     * @mbg.generated Fri Mar 27 23:39:21 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verification.ID
     *
     * @param id the value for verification.ID
     *
     * @mbg.generated Fri Mar 27 23:39:21 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verification.PHONE_NUMBER
     *
     * @return the value of verification.PHONE_NUMBER
     *
     * @mbg.generated Fri Mar 27 23:39:21 CST 2020
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verification.PHONE_NUMBER
     *
     * @param phoneNumber the value for verification.PHONE_NUMBER
     *
     * @mbg.generated Fri Mar 27 23:39:21 CST 2020
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verification.CODE
     *
     * @return the value of verification.CODE
     *
     * @mbg.generated Fri Mar 27 23:39:21 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verification.CODE
     *
     * @param code the value for verification.CODE
     *
     * @mbg.generated Fri Mar 27 23:39:21 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verification.GMT_CREATE
     *
     * @return the value of verification.GMT_CREATE
     *
     * @mbg.generated Fri Mar 27 23:39:21 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verification.GMT_CREATE
     *
     * @param gmtCreate the value for verification.GMT_CREATE
     *
     * @mbg.generated Fri Mar 27 23:39:21 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}