CREATE TABLE USER
(
	ID BIGINT AUTO_INCREMENT,
	ACCOUNT_ID VARCHAR(100),
	NAME VARCHAR(50),
	TOKEN CHAR(36),
	GMT_CREATE BIGINT,
	GMT_MODIFIED BIGINT,
	BIO VARCHAR(256),
	AVATAR_URL VARCHAR(100),
	CONSTRAINT USER_PK
		PRIMARY KEY (ID)
);