CREATE TABLE QUESTION
(
	ID BIGINT AUTO_INCREMENT,
	TITLE VARCHAR(50),
	DESCRIPTION TEXT,
	GMT_CREATE BIGINT,
	GMT_MODIFIED BIGINT,
	CREATOR BIGINT,
	COMMENT_COUNT INT DEFAULT 0,
	VIEW_COUNT INT DEFAULT 0,
	THUMB_COUNT INT DEFAULT 0,
	TAGS VARCHAR(256),
	CONSTRAINT QUESTION_PK
		PRIMARY KEY (ID)
);