CREATE TABLE COMMENT
(
	ID BIGINT AUTO_INCREMENT,
	PARENT_ID BIGINT NOT NULL,
	TYPE INT,
	REVIEWER BIGINT,
	GMT_CREATE BIGINT,
	GMT_MODIFIED BIGINT,
	THUMB_COUNT INT DEFAULT 0,
	CONTENT VARCHAR(1024),
	SUB_COMMENT_COUNT INT DEFAULT 0,
	CONSTRAINT COMMENT_PK
		PRIMARY KEY (ID)
);