CREATE TABLE NOTIFICATION
(
	ID BIGINT AUTO_INCREMENT,
	NOTIFIER BIGINT,
	RECEIVER BIGINT,
	OUTER_ID BIGINT,
	TYPE INT,
	GMT_CREATE BIGINT,
	STATUS INT DEFAULT 0,
	NOTIFIER_NAME VARCHAR(50),
	OUTER_TITLE VARCHAR(256),
	CONSTRAINT NOTIFICATION_PK
		PRIMARY KEY (ID)
);